name: pack

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-slim
        
        steps:
            - uses: actions/checkout@v2
            - name: use node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: yarn
            - name: build
              run: yarn build
