name: pack

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: use node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: cache node_modules
              uses: actions/cache@v2
              with:
                path: ~/.npm
                key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.OS }}-node-
                    ${{ runner.OS }}-
            - name: install dependencies
              run: yarn
            - name: build
              run: yarn build
            # - name: archive artifacts
            #   uses: actions/upload-artifact@v2
            #   with:
            #     name: docs
            #     path: |
            #         docs
            - name: push docs
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git push origin :docs
                git checkout --orphan docs
                git branch -a
                git add docs
                git commit docs -m 'push docs files'
                git push origin docs:docs
