name: pack

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: use node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: yarn
            - name: build
              run: yarn build
            - name: archive artifacts
              uses: actions/upload-artifact@v2
              with:
                name: docs
                path: |
                    docs
            - name: ls
              run: ls
            - name: push docs branch
              run: git branch -a
